name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          
      - name: Install Dependencies
        run: npm install

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine wine32 wine64 libwine libwine:i386 fonts-wine

      - name: Build Application
        run: npm run dist
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: release-files
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: release-files
          path: dist

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}